import Anthropic from '@anthropic-ai/sdk';
import fs from 'fs';
import dotenv from 'dotenv';
dotenv.config();

const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

// This simulates a real failed test log
// In a real project this would be read from your test results automatically
const failedTestLog = `
Test: "complete end to end purchase flow"
Status: FAILED
Duration: 8.3s
Error: Timeout 30000ms exceeded

  Page URL: https://www.saucedemo.com/checkout-step-one.html
  
  Expected: locator('[data-test="continue"]') to be visible
  Received: Element not found after 30000ms

  at checkout.spec.js:45

  Browser: Chromium
  OS: MacOS
  Viewport: 1280x720
  
  Console errors detected:
  - TypeError: Cannot read property 'click' of null
  - Network request failed: POST /api/checkout 503 Service Unavailable
`;

async function generateBugReport() {
  console.log('Sending failed test log to Claude API...\n');

  const message = await client.messages.create({
    model: 'claude-opus-4-5',
    max_tokens: 1500,
    messages: [
      {
        role: 'user',
        content: `You are a senior QA engineer. Convert this failed test log 
into a professional bug report that a developer can act on immediately.

Failed test log:
${failedTestLog}

Write the bug report with these exact sections:
**Bug Title:**
**Environment:**
**Severity:** (Critical / High / Medium / Low)
**Priority:** (P1 / P2 / P3 / P4)
**Steps to Reproduce:**
**Expected Result:**
**Actual Result:**
**Error Details:**
**Possible Root Cause:**
**Suggested Fix:**
**Attachments:** (list what should be attached)

Be specific, technical, and professional.`
      }
    ]
  });

  const bugReport = message.content[0].text;

  console.log('AI Generated Bug Report:\n');
  console.log(bugReport);

  const timestamp = new Date().toISOString().split('T')[0];
  const filename = `reports/bug-report-${timestamp}.md`;

  fs.writeFileSync(filename, 
    `# Bug Report\nGenerated by AI on ${timestamp}\n\n${bugReport}`
  );

  console.log(`\n✅ Bug report saved to ${filename}`);
}

generateBugReport();